# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/JClinic',
                'doc_host': 'https://ulupo.github.io',
                'git_url': 'https://github.com/ulupo/JClinic',
                'lib_path': 'jclinic'},
  'syms': {'jclinic.core': {'jclinic.core.foo': ('core.html#foo', 'jclinic/core.py')}}}
